name: opencode-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Enable detailed logs
        env:
          ACTIONS_STEP_DEBUG: "true"
        run: echo "Debug enabled"
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: anomalyco/opencode/github@0.2.0
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USE_GITHUB_TOKEN: "false"
        with:
          model: openrouter/anthropic/claude-3.5-sonnet
          use_github_token: false
          prompt: |
            Revise este pull request:
            - Verifique problemas de qualidade de código
            - Procure por potenciais bugs
            - Sugira melhorias
